all:
	javac -target 1.6 -source 1.6 SonoranCellular/utils/*.java
	javac -target 1.6 -source 1.6 SonoranCellular/servlets/*.java

clean:
	-/bin/rm SonoranCellular/utils/*.class SonoranCellular/servlets/*.class
